'use client'
import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'
const KEYS=[['top_stats','Top bar'],['headline_1','Headline 1'],['headline_2','Headline 2 italic'],['headline_3','Headline 3 orange'],['subtext_1','Subtext 1'],['subtext_2','Subtext 2'],['cta_join','Join button'],['cta_private','Private button'],['stat1_num','Stat1 num'],['stat1_label','Stat1 label'],['stat2_num','Stat2 num'],['stat2_label','Stat2 label'],['stat3_num','Stat3 num'],['stat3_label','Stat3 label'],['featured_label','Featured label'],['footer_left','Footer']]
export default function Admin(){
  const [rows,setRows]=useState<any[]>([])
  const [feat,setFeat]=useState<any>({title:'Kissa Tanaka',area:'SOHO',time:'TONIGHT 7:30PM',spots_left:3,host_label:'HOST: COMEDIAN · GOLD',price_label:'$$ · CREATIVE MINDS',vibe_label:'SOHO · KISSATEN',invite_text:'CJ INVITES YOU...',description_long:'A 6-seat counter...',image_url:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200'})
  const load=async()=>{const {data}=await supabase.from('site_content').select('*'); if(data) setRows(data); const {data:f}=await supabase.from('featured_events').select('*').limit(1); if(f&&f[0]) setFeat(f[0])}
  useEffect(()=>{load()},[])
  return(<main className="min-h-screen bg-black text-white p-8 max-w-5xl mx-auto"><h1 className="mono text-xs">ADMIN - ALL TEXT EDITABLE + BUTTONS WIRED PER BIBLE</h1><div className="mt-6 grid gap-3">{KEYS.map(([k,l])=>{const v=rows.find(r=>r.key===k)?.value||''; return(<div key={k} className="grid grid-cols-[180px_1fr_60px] gap-2 items-center"><span className="mono text-[10px] text-zinc-500">{l}</span><input id={k} defaultValue={v} className="bg-zinc-900 border border-zinc-800 rounded-xl p-2 text-xs"/><button onClick={async()=>{const val=(document.getElementById(k) as HTMLInputElement).value; await supabase.from('site_content').upsert({key:k,value:val},{onConflict:'key'}); load()}} className="bg-white text-black rounded-xl h-8 text-[10px]">SAVE</button></div>)})}</div><div className="mt-10 bg-zinc-900 border border-zinc-800 rounded-2xl p-6"><h2 className="mono text-xs">FEATURED CARD</h2><div className="mt-4 grid grid-cols-2 gap-3">{Object.keys(feat).filter(k=>!['id','created_at'].includes(k)).map(key=><div key={key} className="flex flex-col"><label className="mono text-[9px] text-zinc-500">{key}</label><input value={feat[key]} onChange={e=>setFeat({...feat,[key]: key==='spots_left'?Number(e.target.value):e.target.value})} className="bg-black border border-zinc-800 rounded-xl p-2 text-xs"/></div>)}</div><button onClick={async()=>{const {data:ex}=await supabase.from('featured_events').select('id').limit(1); if(ex&&ex[0]) await supabase.from('featured_events').update(feat).eq('id',ex[0].id); else await supabase.from('featured_events').insert(feat); alert('Saved')}} className="mt-4 bg-[#c96a4a] text-white px-6 h-10 rounded-xl mono text-[10px]">SAVE FEATURED</button></div><pre className="mt-6 bg-black p-4 rounded-xl text-[10px] text-zinc-600">create table if not exists site_content (key text primary key, value text); create table if not exists featured_events (id uuid primary key default gen_random_uuid(), created_at timestamp default now(), title text, area text, time text, spots_left int, host_label text, price_label text, vibe_label text, invite_text text, description_long text, image_url text);</pre></main>)
}